sampletable: 'config/sampletable.tsv'

references:
  genome: '../annotation/data/ecoli_default.fasta'
  bwi_index: '../annotation/data/ecoli_default.fasta.bwt'
  annotation: '../annotation/data/ecoli_default.patch1.gff'

circos_conf: 'config/RILseq-master/data/E_coli_K12/ver2/draw_links.conf'
