import sys
import os
from textwrap import dedent
import yaml
import tempfile
import pandas as pd
import numpy as np

configfn = 'config/config.yaml'
config = yaml.safe_load(open(configfn))

sampletable = pd.read_csv('config/sampletable.tsv', sep='\t')

genome_fa = config['references_dir'] + '/' + \
    config['organism'] + '/' + \
    config['aligner']['tag'] + '/genome/bwa-mem/' + \
    config['organism'] + \
    '_' + \
    config['aligner']['tag'] + \
    '.fasta'

genome_gff = '../references/references_data/ecoli/default/annotation/ecoli_default.gtf'


# ----------------------------------------------------------------------------
# TARGETS
# ----------------------------------------------------------------------------

rule targets:
    """
    Final targets to create
    """
    input:
        expand('data/rnaseq_rilseq/{sample}/{sample}_{frac}_fragments.txt',
               sample=sampletable['samplename'], frac=['all', 'significant']),
        expand('data/rnaseq_rilseq/{sample}/{sample}_{frac}.bed',
               sample=sampletable['samplename'], frac=['all', 'significant']),
        expand('data/rnaseq_rilseq/{sample}/{sample}_circos_plot.svg',
               sample=sampletable['samplename']),
        expand('data/rnaseq_rilseq/{sample}/{sample}_R1.cutadapt.fastq_bwa.bam.rillibsize',
               sample=sampletable['samplename']),
        # unified samples
        expand('data/rnaseq_rilseq/{sample}_unified/{sample}_unified_{frac}_fragments.txt',
               sample=sampletable['group'], frac=['all', 'significant']),
        expand('data/rnaseq_rilseq/{sample}/{sample}_{frac}.bed',
               sample=sampletable['group']+'_unified', frac=['all', 'significant']),
        expand('data/rnaseq_rilseq/{sample}/{sample}_circos_plot.svg',
               sample=sampletable['group']+'_unified'),
        expand('data/rnaseq_rilseq/{sample}/{sample}_R1.cutadapt.fastq_bwa.bam.rillibsize',
               sample=sampletable['group']+'_unified'),





# ----------------------------------------------------------------------------
# RULES
# ----------------------------------------------------------------------------


rule map_single_fragments:
    input:
        r1 = 'data/rnaseq_samples/{sample}/{sample}_R1.cutadapt.fastq.gz',
        r2 = 'data/rnaseq_samples/{sample}/{sample}_R2.cutadapt.fastq.gz',
        fa = genome_fa,
        gff = genome_gff,
        fai = genome_fa + '.bwt'
    log:
        'logs/map_single_fragments_{sample}.log'
    output:
        'data/rnaseq_rilseq/{sample}/{sample}_R1.cutadapt.fastq_bwa.bam',
        'data/rnaseq_rilseq/{sample}/{sample}_R1.cutadapt.fastq_bwa.bam.bai'
    threads: 8
    resources:
        mem_mb=32*1024,
        disk_mb=32*1024,
        runtime=240
    params:
        dirout = 'data/rnaseq_rilseq/{sample}'
    shell:
        'map_single_fragments.py  '
        '{input.fa} '
        '-g {input.gff} '
        '-1 {input.r1} '
        '-2 {input.r2} '
        '-d {params.dirout} '
        '-o {wildcards.sample} '
        '-r '
        '--feature exon '
        '--create_wig '


rule libsize:
    input:
        bam = 'data/rnaseq_rilseq/{sample}/{sample}_R1.cutadapt.fastq_bwa.bam',
    log:
        'logs/libsize_{sample}.log'
    output:
        'data/rnaseq_rilseq/{sample}/{sample}_R1.cutadapt.fastq_bwa.bam.rillibsize'
    threads: 1
    resources:
        mem_mb=4*1024,
        disk_mb=4*1024,
        runtime=2*60
    shell:
        'samtools view -c {input.bam} > {output[0]}; '
        'samtools view -c -F 260 {input.bam} >> {output[0]}'


rule map_chimeric_fragments:
    input:
        bam = 'data/rnaseq_rilseq/{sample}/{sample}_R1.cutadapt.fastq_bwa.bam',
        bai = 'data/rnaseq_rilseq/{sample}/{sample}_R1.cutadapt.fastq_bwa.bam.bai',
        fa = genome_fa,
        gff = genome_gff
    log:
        'logs/map_chimeric_fragments_{sample}.log'
    output:
        'data/rnaseq_rilseq/{sample}/{sample}_all_fragments.txt'
    threads: 64
    resources:
        mem_mb=128*1024,
        disk_mb=128*1024,
        runtime=24*60
    params:
        dirout = 'data/rnaseq_rilseq/{sample}'
    shell:
        'map_chimeric_fragments.py '
        '--dirout {params.dirout} '
        '-r '       # reverse stranded library
        '-t {input.gff} '
        '--params_aln  "-t {threads} -N -M 0" '
        '{input.fa} '
        '{input.bam} '
        '> {output[0]} '


rule significant_regions:
    input:
        txt = 'data/rnaseq_rilseq/{sample}/{sample}_all_fragments.txt',
        bam = 'data/rnaseq_rilseq/{sample}/{sample}_R1.cutadapt.fastq_bwa.bam'
    log:
        'logs/significant_regions_{sample}.log'
    resources:
        mem_mb=32*1024,
        disk_mb=32*1024,
        runtime=240
    output:
        'data/rnaseq_rilseq/{sample}/{sample}_significant_fragments.txt'
    shell:
        'RILseq_significant_regions.py '
        '--total_reverse '  # library is reverse stranded
        '--ribozero '       # Remove rRNA prior to the statistical analysis.')
        '--BC_chrlist "chr" '
        '--total_RNA {input.bam} '      # Normalize in total RNA from these bam files
        '{input.txt} '       # all_fragments.txt
        '> {output[0]} '



rule generate_BED:
    input:
        reads='data/rnaseq_rilseq/{sample}/{sample}_all_fragments.txt',
        fa=genome_fa,
        bam='data/rnaseq_rilseq/{sample}/{sample}_R1.cutadapt.fastq_bwa.bam'
    log:
        'logs/generate_BED_{sample}.log'
    resources:
        mem_mb=128*1024,
        disk_mb=128*1024,
        runtime=120
    output:
        'data/rnaseq_rilseq/{sample}/{sample}_all.bed'
    shell:
        'generate_BED_file_of_endpoints.py '
        '{input.fa} '
        '{input.reads} '
        '{wildcards.sample}_all '
        '{wildcards.sample}_all '
        '{input.bam} '
        '> {output[0]}'

rule generate_BED_sig:
    input:
        reads='data/rnaseq_rilseq/{sample}/{sample}_all_fragments.txt',
        summary='data/rnaseq_rilseq/{sample}/{sample}_significant_fragments.txt',
        fa=genome_fa,
        bam='data/rnaseq_rilseq/{sample}/{sample}_R1.cutadapt.fastq_bwa.bam'
    log:
        'logs/generate_BED_{sample}.log'
    resources:
        mem_mb=128*1024,
        disk_mb=128*1024,
        runtime=120
    output:
        'data/rnaseq_rilseq/{sample}/{sample}_significant.bed'
    shell:
        'generate_BED_file_of_endpoints.py '
        '-s {input.summary} '
        '{input.fa} '
        '{input.reads} '
        '{wildcards.sample}_significant '
        '{wildcards.sample}_significant '
        '{input.bam} '
        '> {output[0]}'


rule prep_interactions_plot:
    """
    This makes the circos plot file, used to later plot the interactions
    """
    input:
        reads='data/rnaseq_rilseq/{sample}/{sample}_all_fragments.txt',
        summary='data/rnaseq_rilseq/{sample}/{sample}_significant_fragments.txt',
    log:
        'logs/prep_interactions_plot_{sample}.log'
    resources:
        mem_mb=64*1024,
        disk_mb=64*1024,
        runtime=120
    output:
        'data/rnaseq_rilseq/{sample}/{sample}_circos_plot.txt'
    shell:
        'plot_circos_plot.py '
        '{input.reads} '
        '-s {input.summary} '
        '> {output[0]}'

rule plot_interactions:
    """
    This plots the circos plot file
    """
    input:
        txt='data/rnaseq_rilseq/{sample}/{sample}_circos_plot.txt',
    log:
        'logs/plot_interactions_{sample}.log'
    conda:
        '../rilseq/env-circos.yml'
    resources:
        mem_mb=1024,
        disk_mb=1024,
        runtime=120
    output:
        'data/rnaseq_rilseq/{sample}/{sample}_circos_plot.svg'
    shell:
        # from ../rilseq/RILseq-master/data/E_coli_K12/plot_interactions.sh:
        'circos '
        '-conf ../rilseq/RILseq-master/data/E_coli_K12/ver2/draw_links.conf '
        '-param links/link/file={input.txt} '
        '-outputfile {output[0]} '


def input_merge_bams(wc):
    """
    Given a group, returns the bam file names of biological replicates
    """
    samples = sampletable.loc[ sampletable['group'] == wc.group, 'samplename']
    return(['data/rnaseq_rilseq/{}/{}_R1.cutadapt.fastq_bwa.bam'.format(sp, sp) for sp in samples])

rule merge_bams:
    input:
        input_merge_bams
    log:
        'logs/merge_bams_{group}.log'
    resources:
        mem_mb=128*1024,
        disk_mb=128*1024,
        runtime=120
    output:
        'data/rnaseq_rilseq/{group}_unified/{group}_unified_R1.cutadapt.fastq_bwa.bam'
    shell:
        'samtools merge -o {output[0]} {input} '
        '&> {log[0]}'

rule index_merged_bams:
    input:
        'data/rnaseq_rilseq/{group}_unified/{group}_unified_R1.cutadapt.fastq_bwa.bam'
    log:
        'logs/index_merged_bams_{group}.log'
    resources:
        mem_mb=128*1024,
        disk_mb=128*1024,
        runtime=120
    output:
        'data/rnaseq_rilseq/{group}_unified/{group}_unified_R1.cutadapt.fastq_bwa.bam.bai'
    shell:
        'samtools index {input[0]} '
        '&> {log[0]}'








# vim: ft=python
