# start from reference annotation
patch0:
  file: prepared-input/ecoli_default_minus_sRNA.gtf
  description: 'reference annotation used in Adams et al., 2021 PMID: 33460557; contains mRNAs, rRNAs and tRNAs.'

# list of sRNAs to add
patch1:
  file: prepared-input/ecoli_sRNA.bed
  description: 'list of known sRNAs in E. coli, manually prepared'
