sampletable: 'config/sampletable.tsv'

patterns: 'config/rnaseq_patterns.yaml'

# Which key in the `references` dict below to use
organism: 'ecoli'

# If not specified here, use the environment variable REFERENCES_DIR.
references_dir: '../references/references_data'

stranded: 'fr-firststrand'

aligner:
  index: 'bwa-mem'
  tag: 'default'

rrna:
  index: 'bowtie2'
  tag: 'rRNA'

gtf:
  tag: "default"

salmon:
  tag: "default"

kallisto:
  tag: "default"

fastq_screen:
  - label: Ecoli
    organism: ecoli
    tag: default
  - label: rRNA
    organism: ecoli
    tag: rRNA

#merged_bigwigs:
#  control_pos:
#    pos:
#      - sample1
#      - sample2
#  treatment_all:
#    pos:
#      - sample3
#      - sample4
#    neg:
#      - sample3
#      - sample4

# See the reference config files in the top level of the repo,
# include/reference_configs, for inspiration for more species.

references:


  ecoli:
    rRNA:
      genome:
        url:
          - 'https://www.arb-silva.de/fileadmin/silva_databases/release_128/Exports/SILVA_128_LSURef_tax_silva_trunc.fasta.gz'
          - 'https://www.arb-silva.de/fileadmin/silva_databases/release_128/Exports/SILVA_128_SSURef_Nr99_tax_silva_trunc.fasta.gz'
        postprocess:
          function: 'lib.common.filter_fastas'
          args: 'Escherichia coli'
        indexes:
            - 'hisat2'
            - 'bowtie2'

    default:
      genome:
        url: 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_genomic.fna.gz'
        postprocess:
          function: 'lib.postprocess.ecoli.to_chr'

        indexes:
          - 'bowtie2'
          - 'bwa-mem'

      annotation:
        url: 'file://../annotation/data/ecoli_default.patch1.gff'
        postprocess:
          function: 'lib.common.gzipped'
        conversions:
          - 'refflat'
          - 'bed12'
          - 'mappings'

      transcriptome:
        indexes:
          - 'salmon'
          - 'kallisto'

#include_references:
#  - '../../include/reference_configs/test.yaml'
#  - '../../include/reference_configs/Drosophila_melanogaster.yaml'

